server:
  port: 8081

spring:
  profiles:
    active: console
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    stream:
      function:
        definition: processInputStream
      bindings:
        processInputStream-in-0:
          destination: input-data
        processInputStream-out-0:
          destination: empty-data
        processInputStream-out-1:
          destination: json-data
        processInputStream-out-2:
          destination: text-data
      kafka:
        streams:
          binder:
            configuration:
              max:
                poll:
                  records: 100
              commit:
                inverval: 500
              processing:
                guarantee: exactly_once
            functions:
              processInputStream:
                applicationId: kafkaStreamsServiceAppId
          bindings:
            processInputStream-in-0:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                concurrency: 20
                deserializationExceptionHandler: logAndContinue
                startOffset: latest
            processRawDataStream-out-0:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.springframework.kafka.support.serializer.JsonSerde
            processRawDataStream-out-1:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
            processRawDataStream-out-2:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde