server:
  port: ${bootstrap-config.app.port}

spring:
  kafka:
    bootstrap-servers: ${bootstrap-config.kafka.bootstrap-servers}
  cloud:
    stream:
      function:
        definition: processUsersStream;processRetryUsersStream
      bindings:
        processUsersStream-in-0:
          destination: ${bootstrap-config.kafka.topics.users}
        processUsersStream-out-0:
          destination: ${bootstrap-config.kafka.topics.valid-users}
        processUsersStream-out-1:
          destination: ${bootstrap-config.kafka.topics.dlq}
        processRetryUsersStream-in-0:
          destination: ${bootstrap-config.kafka.topics.users-retry}
        processRetryUsersStream-out-0:
          destination: ${bootstrap-config.kafka.topics.valid-users}
        processRetryUsersStream-out-1:
          destination: ${bootstrap-config.kafka.topics.dlq}
      kafka:
        streams:
          binder:
            configuration:
              max:
                poll:
                  records: ${bootstrap-config.kafka.max-poll-records}
              commit:
                interval:
                  ms: ${bootstrap-config.kafka.commit-interval-ms}
              processing:
                guarantee: exactly_once_v2
              isolation:
                level: read_committed
              compression:
                type: snappy
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.springframework.kafka.support.serializer.JsonSerde
              spring:
                json:
                  value:
                    default:
                      type: com.fasterxml.jackson.databind.node.ObjectNode
            functions:
              processUsersStream:
                applicationId: ValidationApplicationId
              processRetryUsersStream:
                applicationId: RetryValidationApplicationId
          bindings:
            processUsersStream-in-0:
              consumer:
                concurrency: ${bootstrap-config.kafka.concurrency.users-stream}
                deserializationExceptionHandler: logAndContinue
            processRetryUsersStream-in-0:
              consumer:
                concurrency: ${bootstrap-config.kafka.concurrency.retry-users-stream}
                deserializationExceptionHandler: logAndContinue

bootstrap-config:
  app:
    port: 8084
  kafka:
    bootstrap-servers: localhost:9092
    max-poll-records: 300
    commit-interval-ms: 1000
    topics:
      users: com-example-users
      users-retry: com-example-users-retry
      valid-users: com-example-valid-users
      dlq: com-example-dlq
    concurrency:
      users-stream: 10
      retry-users-stream: 2

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      cache:
        time-to-live: 10s
      show-components: always