server:
  port: ${bootstrap-config.app.port}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

bootstrap-config:
  app:
    port: 8080
  kafka:
    bootstrap-servers: localhost:9092
    producer-client-id: ingress-controller
    producer-batch-size: 10000
    topic:
      target: com-example-users